db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=prueba
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./db:/var/lib/mysql