SELECT E.LAST_NAME AS 'EMPLOYEE', E.HIRE_DATE AS 'EMP HIRED', M.LAST_NAME AS 'MANAGER', M.HIRE_DATE AS 'MGR HIRED'
FROM employees E
JOIN employees M
ON (E.MANAGER_ID = M.EMPLOYEE_ID)
WHERE E.HIRE_DATE <= M.HIRE_DATE;
