SELECT E.LAST_NAME, E.JOB_ID, D.DEPARTMENT_NAME, E.SALARY, G.GRADE_LEVEL
FROM employees AS 'E'
JOIN departments AS 'D'
ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
JOIN job_grades AS 'G'
ON (E.SALARY >= G.LOWEST_SAL AND E.SALARY <= G.HIGHEST_SAL);
