SELECT EMPLOYEE_ID, LAST_NAME, DEPARTMENT_ID
FROM employees
WHERE DEPARTMENT_ID IN
	( SELECT DEPARTMENT_ID 
      FROM departments
      WHERE LOCATION_ID IN
		( SELECT LOCATION_ID
          FROM locations
          WHERE CITY LIKE 'T%') );