SELECT LAST_NAME, HIRE_DATE, SALARY
FROM employees
WHERE ( LAST_NAME, SALARY ) IN
	( SELECT LAST_NAME, SALARY
      FROM employees
      WHERE  JOB_ID NOT LIKE 'SA_MAN'
      AND SALARY >
		( SELECT SALARY
          FROM employees 
          WHERE JOB_ID LIKE 'SA_MAN') )
ORDER BY SALARY DESC;