SELECT LAST_NAME AS 'ENAME', SALARY, DEPARTMENT_ID 'DEPTNO', AVG(SALARY) AS 'DEPT_AVG'
FROM employees
WHERE SALARY > 
	( SELECT AVG(SALARY) AS 'SALARY'
	  FROM departments )
GROUP BY DEPTNO
ORDER BY DEPT_AVG;