SELECT LAST_NAME, DEPARTMENT_ID, SALARY
FROM employees
WHERE ( SALARY, COMMISSION_PCT ) IN
	( SELECT SALARY, COMMISSION_PCT
      FROM employees
      WHERE DEPARTMENT_ID IN
		( SELECT DEPARTMENT_ID
          FROM departments 
          WHERE LOCATION_ID = 1700) );