CREATE VIEW SALARY_VU
AS
    SELECT E.LAST_NAME AS 'EMPLOYEE', D.DEPARTMENT_NAME AS 'DEPARTMENT', E.SALARY AS 'SALARY', J.GRADE_LEVEL AS 'GRADE'
    FROM E.employees
    JOIN D.departments
        ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    JOIN J.job_grades
        ON E.SALARY BEWTEEN J.MIN_SALARY AND J.MAX_SALARY;
